### ISSUE TITLE
Goal Tracker

### ISSUE THREAD

**Issue by thejaneofalltrades** [GuildCrafts/web-development-js#24]
## Description

Habits are hard to form!

This goal tracking application can measure how consistently a user completes their desired improvements and allows them to remain accountable for their defined objectives. 

Build a simple application where a user could define their goals, be it at a day-to-day, short-term, or long-term frequency. The user records goal completion with a press of an icon. As time progresses, the user can see the aggregated data of goals completed & otherwise.
## Context

This is a simple, straight-forward project that covers a lot of key concepts in web development:
- Managing a stateful resource that users can create, read, update, and delete (CRUD)
- Graphical rendering of timeline data
- User authentication
## Specifications
- [ ] Users can sign up & sign in
- [ ] Users can CRUD goals
- [ ] Users can record when they accomplish the goal
- [ ] Users can see a graph of how often they completed their goals
### Required

_Do not remove these specs - they are required for all goals_.
- [ ] The artifact produced is properly licensed, preferably with the [MIT license](https://opensource.org/licenses/MIT).

---

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
<br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
